FROM node:18
WORKDIR /jennings_rylee_site
RUN npm install -g create-react-app
RUN npx create-react-app codin1
WORKDIR /jennings_rylee_site/codin1
COPY App.jsx src/App.jsx
RUN npm install
EXPOSE 3000
CMD [ "npm", "start"]